export default  {
    en: {
        title: 'Make the payment',
        card: 'Card number',
        proceed: 'Proceed',
        remove: 'Remove cart',
        january: 'January',
        february: 'February',
        march: 'March',
        april: 'April',
        may: 'May',
        june: 'June',
        july: 'July',
        august: 'August',
        september: 'September',
        october: 'October',
        november: 'November',
        december: 'December'  
    },
    es: {
        title: 'Realizar el pago',
        card: 'Tarjeta de crédito',
        proceed: 'Proceder',
        remove: 'Eliminar carrito',
        january: 'Enero',
        february: 'Febreo',
        march: 'Marzo',
        april: 'Abril',
        may: 'Mayo',
        june: 'Junio',
        july: 'Julio',
        august: 'Agosto',
        september: 'Septiembre',
        october: 'Octubre',
        november: 'Noviembre',
        december: 'Diciembre'  
    },
    ca: {
        title: 'Realitzar el pagament',
        card: 'Targeta de crèdit',
        proceed: 'Procedir',
        remove: 'Eliminar cistella',
        january: 'Gener',
        february: 'Febrer',
        march: 'Març',
        april: 'Abril',
        may: 'Maig',
        june: 'Juny',
        july: 'Juliol',
        august: 'Agost',
        september: 'Setembre',
        october: 'Octubre',
        november: 'Novembre',
        december: 'Desembre'
    },
    ga: {
        title: 'Fai o pagamento',
        card: 'Tarjeta de crédito',
        proceed: 'Continuar',
        remove: 'Elimina a cesta',
        january: 'Enero',
        february: 'Febrero',
        march: 'Marzo',
        april: 'Abril',
        may: 'Mayo',
        june: 'Junio',
        july: 'Julio',
        august: 'Agosto',
        september: 'Septiembre',
        october: 'Octubre',
        november: 'Noviembre',
        december: 'Diciembre'    
    }
}