module.exports = {
    registerUser: require('./register-user'),
    authenticateUser: require('./authenticate-user'),
    retrieveUser: require('./retrieve-user'),
    updateUser: require('./update-user'),
    removeUser: require('./remove-user'),
    createRootDir: require('./create-root-dir'),
    createFile: require('./create-file'),
    createDir: require('./create-dir'),
    retrieveFile: require('./retrieve-file'),
    updateFile: require('./update-file'),
    retrieveDir: require('./retrieve-dir'),
    updatePosition: require('./update-position'),
    removeDir: require('./remove-dir'),
    rename: require('./rename'),
    retrieveLevel: require('./retrieve-level'),
    removeFile: require('./remove-file'),
    moveFile: require('./move-file'),
    moveDir: require('./move-dir')
}